CREATE USER 'novemberizing'@'localhost' IDENTIFIED BY 'helloworld@17';
GRANT ALL ON *.* TO 'novemberizing'@'localhost';
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'novemberizing@21';

USE xchat;

DELIMITER //
CREATE PROCEDURE REGISTER_USER(IN EMAIL VARCHAR(128), IN USERNAME VARCHAR(64), IN DETAIL TEXT)
BEGIN
	DECLARE USERID INT;
    DECLARE ROOMID INT;
	DECLARE CONTINUE HANDLER FOR SQLSTATE '23000'
    BEGIN
		SET USERID = (SELECT `id` FROM TB_USER WHERE email=EMAIL LIMIT 1);
    END;
	INSERT INTO TB_USER (`email`,`name`,`description`, `like`, `datetime`) VALUES (EMAIL, USERNAME, DETAIL, 5, CURRENT_TIMESTAMP());
	SET USERID = LAST_INSERT_ID();
	INSERT INTO TB_ROOM (`id`, `datetime`) VALUES (USERID, CURRENT_TIMESTAMP());
	INSERT INTO TB_ROOMUSER (`userid`, `roomid`, `datetime`) VALUES (USERID, USERID, CURRENT_TIMESTAMP());
END //
DELIMITER ;

