CREATE USER 'novemberizing'@'localhost' IDENTIFIED BY 'helloworld@17';
GRANT ALL ON *.* TO 'novemberizing'@'localhost';
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'novemberizing@21';

USE xchat;

DROP PROCEDURE REGISTER_USER;

DELIMITER //
CREATE PROCEDURE REGISTER_USER(IN EMAIL VARCHAR(128), IN USERNAME VARCHAR(64), IN DETAIL TEXT)
BEGIN
	DECLARE USERID INT;
    DECLARE ROOMID INT;
	DECLARE CONTINUE HANDLER FOR SQLSTATE '23000' BEGIN END;
	INSERT INTO TB_USER (`email`,`name`,`description`, `like`, `datetime`) VALUES (EMAIL, USERNAME, DETAIL, 5, CURRENT_TIMESTAMP());
	SELECT `id` FROM TB_USER WHERE TB_USER.`email` = EMAIL;
END //
DELIMITER ;

DROP PROCEDURE CREATE_ROOM;

DELIMITER //
CREATE PROCEDURE CREATE_ROOM(IN USERID INT)
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '23000' BEGIN END;
	INSERT INTO TB_ROOM (`id`, `datetime`) VALUES (USERID, CURRENT_TIMESTAMP());
    INSERT INTO TB_ROOMUSER (`userid`, `roomid`, `datetime`) VALUES (USERID, USERID, CURRENT_TIMESTAMP());
    SELECT USERID;
END //
DELIMITER ;

DROP PROCEDURE DELETE_ROOM;

DELIMITER //
CREATE PROCEDURE DELETE_ROOM(IN USERID INT)
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '23000' BEGIN END;
    DELETE FROM TB_ROOMUSER WHERE TB_ROOMUSER.userid = USERID;
    -- TODO: SELECT COUNT ROOM'S USER IS ZERO
    DELETE FROM TB_ROOM WHERE TB_ROOM.id = USERID;
    SELECT USERID;
END //
DELIMITER ;

