-- MySQL Script generated by MySQL Workbench
-- Mon Dec 20 14:14:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema xchat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `xchat` ;

-- -----------------------------------------------------
-- Schema xchat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xchat` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `xchat` ;

-- -----------------------------------------------------
-- Table `TB_MESSAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_MESSAGE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TB_MESSAGE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roomid` INT NOT NULL,
  `userid` INT NOT NULL,
  `type` INT NOT NULL DEFAULT 0,
  `message` TEXT NOT NULL,
  `datetime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TB_ROOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_ROOM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TB_ROOM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TB_ROOMUSER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_ROOMUSER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TB_ROOMUSER` (
  `roomid` INT NOT NULL,
  `userid` INT NOT NULL,
  `datetime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`roomid`, `userid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TB_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TB_USER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TB_USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NOT NULL,
  `like` INT NOT NULL DEFAULT 0,
  `datetime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `TB_USER` (`email` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
